### ISSUE TITLE
need update to socket.io 3

### ISSUE THREAD

**Issue by DonBooth** [adeelibr/node-playground#2]
Working through the tutorial.
received the following error: import socketio from "socket.io"
SyntaxError: The requested module 'socket.io' does not provide an export name...

When I reverted to socket.io 2.3.0, which is the version you use, I did not receive an error.

thank you. I'm enjoying the tutorial. You give a much more useful introduction to socket.io then I've seen elsewhere.

**Comment by adeelibr** [comment]
@DonBooth glad you liked the tutorial. I am afraid I won't be updating the tutorial. FreeCodeCamp has added a lot of checks now which makes editing/updating my articles a pain. I might right another article for socket ver 3 though (not sure).

**Comment by DonBooth** [comment]
Hey Adeel,

No sweat. Part of learning involves learning how to modify code when dependencies update.

I glanced briefly at v3 and it might be substantial. A good tutorial on socket.io <http://socket.io/> would be a useful contribution to the community. This is a powerful utility but the docs are not great and examples of use are so simple and basic that they’re not that helpful.

Best,

Don Booth
