### ISSUE TITLE
null values in conversation 

### ISSUE THREAD

**Issue by ggichure** [adeelibr/node-playground#4]
hey, great tutorial..Im facing an error when i hit 
[Get] Get recent convesation
`http://localhost:3000/room/565241728497455b966fbc45dc2fa7bd `
same issue in 
`http://localhost:3000/room/565241728497455b966fbc45dc2fa7bd?limit=15&page=0`
i get empty data in conversation
```

{
    "success": true,
    "conversation": [],
    "users": [
        {
            "_id": "5e221be2bbff463cb239ce14278b11b1",
            "firstName": "user1",
            "lastName": "user1",
            "type": "consumer",
            "createdAt": "2021-03-31T22:27:53.203Z",
            "updatedAt": "2021-03-31T22:27:53.203Z",
            "__v": 0
        },
        {
            "_id": "6736f6c9698549da8c77e75f2a784c06",
            "firstName": "user2",
            "lastName": "user2",
            "type": "consumer",
            "createdAt": "2021-03-31T22:28:03.360Z",
            "updatedAt": "2021-03-31T22:28:03.360Z",
            "__v": 0
        }
    ]
}
```

**Comment by Harshitchourasiya** [comment]
@ggichure 
Try Url: http://localhost:3000/room/565241728497455b966fbc45dc2fa7bd?limit=1&page=0
Where limit will be set to 1.
May be you didn't post a message to that chat room or may be there was an error while posting a message to a chatroom.

**Comment by adeelibr** [comment]
thank you @Harshitchourasiya for responding to the OP's query.
